### ISSUE TITLE
Make more intellisense friendly (class + docstrings)

### ISSUE THREAD

**Issue by Samrose-Ahmed** [camptocamp/jsonschema-gentypes#134]
Perhaps I'm missing an option, but could the types generated use a class and docstings, instead of the constructor and comments, which don't show up in intellisense.

E.g. instead of:

```
# A Widget is a blah blah blah.

#  @see https://google.com
Hello = TypedDict(
    "Hello",
    {
        # The ID of the tenant this event is associated with and will be delivered to. For more on tenants @see https://apptrail.com/docs/applications/guide/working-with-tenants.
        #
        # pattern: ^[A-Za-z0-9_\-+=]*$
        #
        # required
        "id": str,
    }
)

```
generate:
```
class Hello(TypedDict):
    """
    A Widget is a blah blah blah.

    @see https://google.com
    """
    
    a: str
    """
    The ID of the widget, blah blah.
    
    pattern: ^[A-Za-z0-9_\-+=]*$
    
    required
    """
```

which enables:

![](https://user-images.githubusercontent.com/9027301/151991179-3b6df19c-74b6-4052-87a7-225d53dc821b.png)

**Comment by sbrunner** [comment]
I will have a look when all the attribute matches the pattern `^[A-Za-z0-9_]+$`

**Comment by bollwyvl** [comment]
Here's a dirty hack for the naive case of well-behaved attribute names.

https://gist.github.com/bollwyvl/77ece68e4f3748b036d71c1572d96c26

Stuff that comes out has issues as-is, but passes `mypy`/`pyflakes` after going through (in order):
- `isort`
- `black`
- [`ssort`](https://github.com/bwhmather/ssort)
- [`docformatter`](https://github.com/PyCQA/docformatter)

My primary interest is getting this all the way through to [sphinx-autodoc-typehints](https://github.com/tox-dev/sphinx-autodoc-typehints), which it seems to do fairly well. Having some additional opinions about comment styles to match different project needs also suggests some ways forward.

From an IDE usage perspective, it _might_ be preferable to have a top-level namespace-y kinda class which held all the constants.
