### ISSUE TITLE
Docstring of objects does not end up in generated code

### ISSUE THREAD

**Issue by untitaker** [camptocamp/jsonschema-gentypes#416]
All typeddicts do not contain any jsonschema description.

There seems to be a pretty serious confusion as to whether `jsonschema_gentypes.Type` is supposed to contain `description` property or whether `_comments` is supposed to be used.

**Comment by sbrunner** [comment]
`jsonschema_gentypes.Type` doesn't have a field named `description` some subclasses have a field named `descriptions`...

**Comment by untitaker** [comment]
@sbrunner TypedDictType has both, uses `descriptions` in `definition()`, but the code invoking it sets `comments`.

**Comment by untitaker** [comment]
Basically I am asking, what is the difference between those two fields? ISTM TypedDictType._comments is not used to generate code at all. Or maybe I am missing something.

**Comment by sbrunner** [comment]
Effectively, some complex types don't use `_comments`.

**Comment by untitaker** [comment]
I think i got it. It seems to me that `_comments` on a TypedDict is used to document its fields (for example: warnings about unsupported `required` are attached to the dict but end up in per-field docs), while description is used to document the type itself. I don't really understand the codeflow but that's why they're not the same thing.
